### ISSUE TITLE
Error: Cannot invoke "umich.ms.datatypes.scancollection.ScanIndex.getNum2scan()" because "ms2idx2" is null

### ISSUE THREAD

**Issue by markmipt** [waterlooms/mstracer#1]
Hi!

I'm trying to test your ms-tracer, but cannot perform "Step 1, initial detection of peptide features."
The mzML file which I'm using is placed here: http://pubdata.theorchromo.ru/tmp_3/ . It is LC-MS1 data from QE HF generated using msconvert. The OS is Linux Arch, Java version is openjdk 15.0.2 2021-01-19 and Python version is 3.6 installed into virtualenv. I've tried both bash script and command java -jar ms-tracer_detect.jar data/your-file-name.mzXML.

The last lines of the output are:
"...
2021-06-23 13:26:31,918 [umich.ms.datatypes.scancollection.ScanIndex]-[DEBUG] Adding scan #2352 to ScanIndex. num2scan map already contained a scan for scanNum: 2352
2021-06-23 13:26:31,918 [umich.ms.datatypes.scancollection.ScanIndex]-[DEBUG] Adding scan #2352 to ScanIndex. num2scan map already contained a scan for scanNum: 2352
2021-06-23 13:26:31,918 [umich.ms.datatypes.scancollection.ScanIndex]-[DEBUG] Adding scan #2353 to ScanIndex. num2scan map already contained a scan for scanNum: 2353
2021-06-23 13:26:31,918 [umich.ms.datatypes.scancollection.ScanIndex]-[DEBUG] Adding scan #2353 to ScanIndex. num2scan map already contained a scan for scanNum: 2353
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "umich.ms.datatypes.scancollection.ScanIndex.getNum2scan()" because "ms2idx2" is null
	at ca.uwaterloo.service.OpenMzxml.init(OpenMzxml.java:137)
	at ca.uwaterloo.service.OpenMzxml.<init>(OpenMzxml.java:30)
	at ca.uwaterloo.service.PepIdentifier.main(PepIdentifier.java:66)
"

Regards,
Mark

**Comment by trackerrr** [comment]
Hello! We recently updated and moved mstracer to docker hub. If you still with to test, please follow the new instruction. If you encounter the same issue, please let us know.

Best,
Xiangyuan
